/*Throw Clause :- Used to throw an Exception explisitly and catch it..*/

class Demo{
	public static void main(String[]args){
		throw new ArithmeticException();
	}
}


/*Exception in thread "main" java.lang.ArithmeticException
        at Demo.main(p1.java:5)
*/